services:
  # Databases
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  # API Gateway
  kong:
    image: kong:3.4
    ports:
      - "8001:8001"
      - "8000:8000"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/kong/kong.yml

  # Core Microservices
  auth-service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    ports:
      - "8010:8010"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  user-service:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    ports:
      - "8011:8011"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  department-service:
    build:
      context: .
      dockerfile: services/departments/Dockerfile
    ports:
      - "8012:8012"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  classes-service:
    build:
      context: .
      dockerfile: services/classes/Dockerfile
    ports:
      - "8004:8004"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
      SERVICE_PORT: 8004
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  subjects-service:
    build:
      context: .
      dockerfile: services/subjects/Dockerfile
    ports:
      - "8005:8005"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
      SERVICE_PORT: 8005
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  semesters-service:
    build:
      context: .
      dockerfile: services/semesters/Dockerfile
    ports:
      - "8006:8006"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
      SERVICE_PORT: 8006
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  exams-service:
    build:
      context: .
      dockerfile: services/exams/Dockerfile
    ports:
      - "8013:8013"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  marks-service:
    build:
      context: .
      dockerfile: services/marks/Dockerfile
    ports:
      - "8014:8014"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  analytics-service:
    build:
      context: .
      dockerfile: services/analytics/Dockerfile
    ports:
      - "8015:8015"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  notification-service:
    build:
      context: .
      dockerfile: services/notifications/Dockerfile
    ports:
      - "8018:8018"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  copo-service:
    build:
      context: .
      dockerfile: services/copo/Dockerfile
    ports:
      - "8026:8026"
    environment:
      DATABASE_URL: postgresql://lms_user:lms_password@postgres:5432/lms_db
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - kong

volumes:
  postgres_data:
  redis_data: